Add log4j configuration to enable logging
This helps to analyse potential issues with running the tests.
Increase log level of loggers for more tracing.

Setting
log4j.logger.org.testcontainers=DEBUG
helped to find out why update to newer version of testcontainers didn't
work (NoClassDefFoundError). It turned out we need to add the dependency
com.github.docker-java:docker-java-transport-zerodep
which is required since testcontainers 1.16.

Change-Id: I9b8da7a3fb0187fe00408902da3da5cac56a9673